---
- name: Install node exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Start node exporter
  service:
    name: prometheus-node-exporter
    enabled: true
    state: started
